### ISSUE TITLE
Generated code crashes

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#110]
I used the possum data set and selected belly as the feature to train on. I dropped the 'Pop' and 'sex' features and left everything else as default. The code got generated. I copied and pasted the code into a local file and ran that file. The script crashed with the following output:
```
case          int64
site          int64
Pop          object
sex          object
age         float64
hdlngth     float64
skullw      float64
totlngth    float64
taill       float64
footlgth    float64
earconch    float64
eye         float64
chest       float64
belly       float64
dtype: object
Traceback (most recent call last):
  File "/Users/holdenerea/repos/ml_code_generator/generatedCode.py", line 53, in <module>
    model = LinearRegression().fit(x_train, y_train)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 684, in fit
    X, y = self._validate_data(
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1074, in check_X_y
    X = check_array(
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 856, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "/Users/holdenerea/repos/ml_code_generator/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 2072, in __array__
    return np.asarray(self._values, dtype=dtype)
ValueError: could not convert string to float: 'other'
```

Note, that the generated code is:
```
## file into a dataframe for later processing
import pandas as pd
dataframe = pd.read_csv("data//possum.csv")
print(dataframe.dtypes)
## describes a summary of a given dataframe
data_description = dataframe.describe()
## get the labels of the data columns
keys = dataframe.keys()
## removes rows with null entries
dataframe.dropna(axis=0,inplace=True)
## get the labels of the data columns
keys = dataframe.keys()
## split the data set into training and test data
y_values = dataframe["belly"]
x_values = dataframe.drop("belly", axis = 1)
## get the labels of the data columns
keys = dataframe.keys()
## split the data set into training and test data
from sklearn.model_selection import train_test_split
import numpy as np
x_train, x_test, y_train, y_test = train_test_split(x_values, y_values,
test_size = 0.19999999999999996, random_state = 200)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)
## Train a linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train, y_train)
## file into a dataframe for later processing
import pandas as pd
dataframe = pd.read_csv("data//possum.csv")
print(dataframe.dtypes)
## describes a summary of a given dataframe
data_description = dataframe.describe()
## get the labels of the data columns
keys = dataframe.keys()
## drop dataset features passed to args param
dataframe = dataframe.drop(['Pop', 'sex'], axis=1)
## removes rows with null entries
dataframe.dropna(axis=0,inplace=True)
## get the labels of the data columns
keys = dataframe.keys()
## split the data set into training and test data
y_values = dataframe["belly"]
x_values = dataframe.drop("belly", axis = 1)
## get the labels of the data columns
keys = dataframe.keys()
## split the data set into training and test data
from sklearn.model_selection import train_test_split
import numpy as np
x_train, x_test, y_train, y_test = train_test_split(x_values, y_values,
test_size = 0.19999999999999996, random_state = 200)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)
## Train a linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train, y_train)
## file into a dataframe for later processing
import pandas as pd
dataframe = pd.read_csv("data//possum.csv")
print(dataframe.dtypes)
## describes a summary of a given dataframe
data_description = dataframe.describe()
## get the labels of the data columns
keys = dataframe.keys()
## drop dataset features passed to args param
dataframe = dataframe.drop(['Pop', 'sex'], axis=1)
## removes rows with null entries
dataframe.dropna(axis=0,inplace=True)
## get the labels of the data columns
keys = dataframe.keys()
## split the data set into training and test data
y_values = dataframe["belly"]
x_values = dataframe.drop("belly", axis = 1)
## get the labels of the data columns
keys = dataframe.keys()
## split the data set into training and test data
from sklearn.model_selection import train_test_split
import numpy as np
x_train, x_test, y_train, y_test = train_test_split(x_values, y_values,
test_size = 0.19999999999999996, random_state = 200)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)
## Train a linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x_train, y_train)
```

**Comment by KD335** [comment]
I don't know why the code was generated 3 times, but for some reason the first time the code is generated (from the first line until the first time a linear regression model is fit) Pop and sex are not removed from the x data. If the line `dataframe = dataframe.drop(['Pop', 'sex'], axis=1)` is added before the data is cleaned on line 10, everything runs fine.

**Comment by kate-holdener** [comment]
I think the reason that code was generated 3 times is because of issue # 40. I'll close it as a duplicate of issue #40
